// ShadowVote deploy script (Midnight testnet).
// =============================================================================
// This builds and submits the contract deployment transaction. The transaction
// is SIGNED BY YOUR WALLET and pays the DUST fee — that step is intentionally
// yours: nothing here can deploy without a funded testnet wallet seed.
//
// Prerequisites (see contract/README notes):
//   1. `npm run compile` has produced managed/shadowvote (JS + ZK keys).
//   2. A proof server is running locally:
//        docker run -p 6300:6300 midnightntwrk/proof-server:latest \
//          midnight-proof-server -v
//   3. Env vars are set (never hard-code secrets — use a .env / shell export):
//        SHADOWVOTE_WALLET_SEED  = your TESTNET wallet seed (hex, BIP32)
//        SHADOWVOTE_ADMIN_SK     = 32-byte hex secret used as your organizer key
//   4. The wallet has testnet DUST from the faucet (docs.midnight.network).
//
// Target SDK: @midnight-ntwrk/midnight-js-* 4.1.1, wallet 5.0.0,
// compact-runtime 0.16.0, compact-js 2.5.1 (Effect-based CompiledContract).
// =============================================================================

import { firstValueFrom } from 'rxjs';
import { WalletBuilder } from '@midnight-ntwrk/wallet';
import { NetworkId as ZswapNetworkId } from '@midnight-ntwrk/zswap';
import { setNetworkId } from '@midnight-ntwrk/midnight-js-network-id';
import { deployContract } from '@midnight-ntwrk/midnight-js-contracts';
import { indexerPublicDataProvider } from '@midnight-ntwrk/midnight-js-indexer-public-data-provider';
import { NodeZkConfigProvider } from '@midnight-ntwrk/midnight-js-node-zk-config-provider';
import { httpClientProofProvider } from '@midnight-ntwrk/midnight-js-http-client-proof-provider';
import { levelPrivateStateProvider } from '@midnight-ntwrk/midnight-js-level-private-state-provider';
import * as CompiledContract from '@midnight-ntwrk/compact-js/effect/CompiledContract';

import { witnesses, createPrivateState } from '../src/witnesses.js';
// Generated by `compact compile`. The Contract *constructor* (class) is what the
// 4.x CompiledContract binding wants — it takes NO arguments (see the contract's
// `constructor()`), so no `args` are passed to deployContract below.
import { Contract } from '../managed/shadowvote/contract/index.js';

// --- Config -----------------------------------------------------------------

const NODE_URL      = process.env.MN_NODE          ?? 'https://rpc.testnet-02.midnight.network';
const INDEXER_URL   = process.env.MN_INDEXER       ?? 'https://indexer.testnet-02.midnight.network/api/v1/graphql';
const INDEXER_WS    = process.env.MN_INDEXER_WS    ?? 'wss://indexer.testnet-02.midnight.network/api/v1/graphql/ws';
const PROOF_SERVER  = process.env.MN_PROOF_SERVER  ?? 'http://127.0.0.1:6300';

const WALLET_SEED   = process.env.SHADOWVOTE_WALLET_SEED; // funded testnet seed (hex)
const ADMIN_SK_HEX  = process.env.SHADOWVOTE_ADMIN_SK;    // 32-byte hex organizer secret

// Where `compact compile` wrote the ZK keys / zkir. Relative to this script's cwd
// (run `npm run deploy` from the contract/ workspace).
const ZK_ASSETS_DIR = 'managed/shadowvote';

function hexToBytes(hex: string): Uint8Array {
  const clean = hex.replace(/^0x/, '');
  if (clean.length % 2 !== 0) throw new Error('hex string has odd length');
  const out = new Uint8Array(clean.length / 2);
  for (let i = 0; i < out.length; i++) out[i] = parseInt(clean.slice(i * 2, i * 2 + 2), 16);
  return out;
}

async function main() {
  // Midnight network id used by the JS providers. In 4.x this is a plain string
  // that must match the bech32m address network segment — testnet addresses are
  // `mn_..._test1…`, so the value is 'test' (NOT 'TestNet'). The wallet builder
  // separately takes the numeric ZswapNetworkId.TestNet enum.
  setNetworkId('test');

  if (!WALLET_SEED)  throw new Error('Set SHADOWVOTE_WALLET_SEED (funded testnet wallet seed, hex).');
  if (!ADMIN_SK_HEX) throw new Error('Set SHADOWVOTE_ADMIN_SK (32-byte hex organizer secret).');

  const adminSk = hexToBytes(ADMIN_SK_HEX);
  if (adminSk.length !== 32) throw new Error('SHADOWVOTE_ADMIN_SK must be exactly 32 bytes.');

  // --- Compiled contract binding (Effect-based, compact-js 2.5.1) ----------
  // make(tag, ctor).pipe(withWitnesses(...), withCompiledFileAssets(<zk dir>))
  const compiledContract = CompiledContract.make('shadowvote', Contract).pipe(
    CompiledContract.withWitnesses(witnesses),
    CompiledContract.withCompiledFileAssets(ZK_ASSETS_DIR),
  );

  // --- Wallet (SIGNS + pays the DUST fee) ----------------------------------
  console.log('Building wallet from seed and syncing with the indexer …');
  const wallet = await WalletBuilder.buildFromSeed(
    INDEXER_URL,
    INDEXER_WS,
    PROOF_SERVER,
    NODE_URL,
    WALLET_SEED,
    ZswapNetworkId.TestNet,
  );
  wallet.start();

  const state = await firstValueFrom(wallet.state());
  console.log('Wallet address:', state.address);

  // --- Providers -----------------------------------------------------------
  const providers = {
    // Reads public ledger state via the indexer (needs a Node WebSocket impl,
    // which the provider supplies by default).
    publicDataProvider: indexerPublicDataProvider(INDEXER_URL, INDEXER_WS),

    // Reads the compiled ZK prover/verifier keys + zkir from the local FS.
    zkConfigProvider: new NodeZkConfigProvider<string>(ZK_ASSETS_DIR),

    // Proves transactions via the local proof server.
    proofProvider: httpClientProofProvider(PROOF_SERVER, new NodeZkConfigProvider<string>(ZK_ASSETS_DIR)),

    // Encrypted local store for this contract's private state (the secret key).
    privateStateProvider: levelPrivateStateProvider({
      accountId: state.address,
      // Simple password provider for a scripted deploy. For anything holding
      // real value, source this from a secret manager, not a constant.
      privateStoragePasswordProvider: () => process.env.SHADOWVOTE_PRIVATE_STORE_PASSWORD ?? 'shadowvote-local-dev',
    }),

    // walletProvider + midnightProvider are backed by the wallet: it balances,
    // proves and submits, and exposes the ZSwap/encryption public keys.
    // VERIFY: this wallet<->provider bridge couples wallet-api transaction types
    // to the midnight-js-protocol types; confirm the method/return shapes against
    // the official example for your installed wallet@5.x before a real run.
    walletProvider: {
      getCoinPublicKey: () => state.coinPublicKey,
      getEncryptionPublicKey: () => state.encryptionPublicKey,
      balanceTx: (tx: any, _ttl?: Date) => wallet.balanceTransaction(tx, []),
    },
    midnightProvider: {
      submitTx: (tx: any) => wallet.submitTransaction(tx),
    },
  } as any; // `as any` only until the wallet bridge above is confirmed.

  // --- Deploy --------------------------------------------------------------
  console.log('Deploying ShadowVote to testnet-02 …');
  const deployed = await deployContract(providers, {
    compiledContract,
    privateStateId: 'shadowVotePrivateState',
    initialPrivateState: createPrivateState(adminSk),
    // No `args`: the contract's constructor() takes no parameters.
  });

  const address = deployed.deployTxData.public.contractAddress;
  console.log('\n✅ Deployed. Contract address:', address);
  console.log('   Explorer: https://explorer.testnet-02.midnight.network/');
  console.log('\nNext: paste this address into frontend/src/lib/contractService.ts');

  await wallet.close();
}

main().catch((err) => {
  console.error('Deploy failed:', err);
  process.exit(1);
});
