// ShadowVote deploy script (Midnight testnet).
// =============================================================================
// ⛔ THIS SCRIPT CANNOT CURRENTLY REACH THE CHAIN. The blocker is in the SDK,
// not in this file. Read this before spending time on it.
//
// `@midnight-ntwrk/wallet` 5.0.0 syncs by opening a GraphQL subscription named
// `viewingUpdates`. That field NO LONGER EXISTS on the Midnight indexer. Checked
// against preprod on 2026-09-25, both API versions:
//
//   POST https://indexer.preprod.midnight.network/api/v{3,4}/graphql
//   { __schema { subscriptionType { fields { name } } } }
//   -> blocks, contractActions, dustGenerations, dustLedgerEvents,
//      dustNullifierTransactions, shieldedNullifierTransactions,
//      shieldedTransactions, unshieldedTransactions, zswapLedgerEvents
//
// i.e. the DUST-era API replaced `viewingUpdates` with `shieldedTransactions`
// and friends. So the wallet's indexer client fails its handshake, retries
// forever, and logs `IndexerClientEvent$ConnectTimeout` — surfacing as a wall of
//   "[] | Timed out trying to connect"
// while `syncProgress` stays `undefined`. 5.0.0 is the NEWEST published version
// (npm view @midnight-ntwrk/wallet versions ends at 5.0.0), so there is no
// upgrade to apply. Endpoints, seed, funding and networking are all fine and
// were each verified independently; none of them is the problem.
//
// This is also the true cause of the older "expected instance of
// LedgerParameters" failures in deploy.log: the wallet learns ledger parameters
// while syncing, and it never synced. The sync wait below turns that confusing
// crash into an honest hang, which is how the real cause was finally found.
//
// HOW TO DEPLOY IN THE MEANTIME: use the app's own "Deploy a new contract"
// button with Lace connected on the target network. Lace ships its own
// up-to-date indexer client, which is why the live preview contract
// (8e60d089…c143d) exists at all. Everything below is correct as far as it goes
// and should work unchanged once a compatible wallet release lands.
// =============================================================================
//
// Prerequisites (see contract/README notes):
//   1. `npm run compile` has produced managed/shadowvote (JS + ZK keys).
//   2. A proof server is running locally:
//        docker run -p 6300:6300 midnightntwrk/proof-server:latest \
//          midnight-proof-server -v
//   3. Env vars are set (never hard-code secrets — use a .env / shell export):
//        SHADOWVOTE_WALLET_SEED  = your TESTNET wallet seed (hex, BIP32)
//        SHADOWVOTE_ADMIN_SK     = 32-byte hex secret used as your organizer key
//   4. The wallet has testnet DUST from the faucet (docs.midnight.network).
//
// Target SDK: @midnight-ntwrk/midnight-js-* 4.1.1, wallet 5.0.0,
// compact-runtime 0.16.0, compact-js 2.5.1 (Effect-based CompiledContract).
// =============================================================================

import { firstValueFrom, filter } from 'rxjs';
import { WalletBuilder } from '@midnight-ntwrk/wallet';
import { NetworkId as ZswapNetworkId } from '@midnight-ntwrk/zswap';
import { setNetworkId } from '@midnight-ntwrk/midnight-js-network-id';
import { MidnightBech32m } from '@midnight-ntwrk/wallet-sdk-address-format';

const NETWORK_ID    = process.env.MN_NETWORK_ID    ?? 'preview';
setNetworkId(NETWORK_ID);

const toNetworkAddress = (bech32Str: string) => {
  const parsed = MidnightBech32m.parse(bech32Str);
  return new MidnightBech32m(parsed.type, NETWORK_ID, parsed.data).asString();
};

import { deployContract } from '@midnight-ntwrk/midnight-js-contracts';
import { indexerPublicDataProvider } from '@midnight-ntwrk/midnight-js-indexer-public-data-provider';
import { NodeZkConfigProvider } from '@midnight-ntwrk/midnight-js-node-zk-config-provider';
import { httpClientProofProvider } from '@midnight-ntwrk/midnight-js-http-client-proof-provider';
import { levelPrivateStateProvider } from '@midnight-ntwrk/midnight-js-level-private-state-provider';
import * as CompiledContract from '@midnight-ntwrk/compact-js/effect/CompiledContract';

import { witnesses, createPrivateState } from '../src/witnesses.js';
// Generated by `compact compile`. The Contract *constructor* (class) is what the
// 4.x CompiledContract binding wants — it takes NO arguments (see the contract's
// `constructor()`), so no `args` are passed to deployContract below.
import { Contract } from '../managed/shadowvote/contract/index.js';

// --- Config -----------------------------------------------------------------

const NODE_URL      = process.env.MN_NODE          ?? 'https://rpc.preprod.midnight.network';
const INDEXER_URL   = process.env.MN_INDEXER       ?? 'https://indexer.preprod.midnight.network/api/v4/graphql';
const INDEXER_WS    = process.env.MN_INDEXER_WS    ?? 'wss://indexer.preprod.midnight.network/api/v4/graphql/ws';
const PROOF_SERVER  = process.env.MN_PROOF_SERVER  ?? 'http://127.0.0.1:6300';

const WALLET_SEED   = process.env.SHADOWVOTE_WALLET_SEED; // funded testnet seed (hex)
const ADMIN_SK_HEX  = process.env.SHADOWVOTE_ADMIN_SK;    // 32-byte hex organizer secret

// Where `compact compile` wrote the ZK keys / zkir. Relative to this script's cwd
// (run `npm run deploy` from the contract/ workspace).
const ZK_ASSETS_DIR = 'managed/shadowvote';

function hexToBytes(hex: string): Uint8Array {
  const clean = hex.replace(/^0x/, '');
  if (clean.length % 2 !== 0) throw new Error('hex string has odd length');
  const out = new Uint8Array(clean.length / 2);
  for (let i = 0; i < out.length; i++) out[i] = parseInt(clean.slice(i * 2, i * 2 + 2), 16);
  return out;
}

async function main() {
  // Midnight network id used by the JS providers.
  setNetworkId(NETWORK_ID);

  if (!WALLET_SEED)  throw new Error('Set SHADOWVOTE_WALLET_SEED (funded testnet wallet seed, hex).');
  if (!ADMIN_SK_HEX) throw new Error('Set SHADOWVOTE_ADMIN_SK (32-byte hex organizer secret).');

  const adminSk = hexToBytes(ADMIN_SK_HEX);
  if (adminSk.length !== 32) throw new Error('SHADOWVOTE_ADMIN_SK must be exactly 32 bytes.');

  // --- Compiled contract binding (Effect-based, compact-js 2.5.1) ----------
  // make(tag, ctor).pipe(withWitnesses(...), withCompiledFileAssets(<zk dir>))
  const compiledContract = CompiledContract.make('shadowvote', Contract).pipe(
    CompiledContract.withWitnesses(witnesses),
    CompiledContract.withCompiledFileAssets(ZK_ASSETS_DIR),
  );

  // --- Wallet (SIGNS + pays the DUST fee) ----------------------------------
  console.log('Building wallet from seed and syncing with the indexer …');
  const wallet = await WalletBuilder.buildFromSeed(
    INDEXER_URL,
    INDEXER_WS,
    PROOF_SERVER,
    NODE_URL,
    WALLET_SEED,
    ZswapNetworkId.TestNet,
  );
  wallet.start();

  // WAIT FOR A REAL SYNC — not a sleep.
  //
  // This used to be `setTimeout(6000)` followed by whatever state happened to
  // be available, and that is what made the earlier deploys fail with
  //   "expected instance of LedgerParameters"
  // from inside wallet.balanceTransaction. The wallet learns the chain's ledger
  // parameters (fee schedule and friends) as part of syncing; ask it to balance
  // before that lands and it calls Transaction.fees(undefined), which the wasm
  // layer rejects with exactly that assertion. Six seconds was simply not long
  // enough on preprod, and any fixed wait is a race.
  //
  // `syncProgress.synced` is the wallet's own answer to "have I caught up",
  // so waiting on it is both correct and as fast as the chain allows.
  console.log(`Syncing wallet with the ${NETWORK_ID} indexer — this can take a few minutes …`);
  const state = await firstValueFrom(
    wallet.state().pipe(
      filter((s) => {
        const p = s.syncProgress;
        if (!p) return false;
        const { applyGap, sourceGap } = p.lag as { applyGap: bigint; sourceGap: bigint };
        if (!p.synced) {
          console.log(`  syncing — ${sourceGap} blocks to fetch, ${applyGap} to apply`);
        }
        return p.synced;
      }),
    ),
  );
  console.log('Synced.');
  console.log('Wallet address:', state.address);
  console.log('Current balances:', JSON.stringify(state.balances));

  // Nothing below can succeed without funds, and failing here names the reason
  // instead of surfacing it as an opaque balancing error several steps later.
  if (Object.keys(state.balances).length === 0) {
    // Derive the faucet address by REBUILDING the bech32m payload under an
    // `addr` type. A string replace on the HRP would leave the checksum
    // describing the old one, and the result would not decode anywhere.
    const cpk = MidnightBech32m.parse(state.coinPublicKey);
    const faucetAddress = new MidnightBech32m('addr', NETWORK_ID, cpk.data).asString();
    throw new Error(
      [
        `This wallet holds no funds on ${NETWORK_ID}, so it cannot pay the deploy fee.`,
        '',
        'Fund this address, wait for it to confirm, then re-run:',
        `  ${faucetAddress}`,
      ].join('\n'),
    );
  }

  // --- Providers -----------------------------------------------------------
  const providers = {
    // Reads public ledger state via the indexer (needs a Node WebSocket impl,
    // which the provider supplies by default).
    publicDataProvider: indexerPublicDataProvider(INDEXER_URL, INDEXER_WS),

    // Reads the compiled ZK prover/verifier keys + zkir from the local FS.
    zkConfigProvider: new NodeZkConfigProvider<string>(ZK_ASSETS_DIR),

    // Proves transactions via the local proof server.
    proofProvider: httpClientProofProvider(PROOF_SERVER, new NodeZkConfigProvider<string>(ZK_ASSETS_DIR)),

    // Encrypted local store for this contract's private state (the secret key).
    privateStateProvider: levelPrivateStateProvider({
      accountId: toNetworkAddress(state.address),
      // Simple password provider for a scripted deploy. For anything holding
      // real value, source this from a secret manager, not a constant.
      privateStoragePasswordProvider: () => process.env.SHADOWVOTE_PRIVATE_STORE_PASSWORD ?? 'shadowvote-local-dev',
    }),

    // walletProvider + midnightProvider are backed by the wallet: it balances,
    // proves and submits, and exposes the ZSwap/encryption public keys.
    walletProvider: {
      getCoinPublicKey: () => toNetworkAddress(state.coinPublicKey),
      getEncryptionPublicKey: () => toNetworkAddress(state.encryptionPublicKey),

      /**
       * Balance the transaction, then PROVE it.
       *
       * wallet@5 changed the shape of this step and the old code here did not
       * follow: `balanceTransaction` no longer returns a transaction, it returns
       * a PROVING RECIPE (`BalanceTransactionToProve | NothingToProve`). The
       * previous version treated that recipe as if it were a transaction and
       * bolted fake `identifiers()` and `serialize()` methods onto it — the
       * latter returning 32 zero bytes — so even had balancing succeeded, what
       * reached the chain would have been garbage.
       *
       * The real contract is three calls: balance -> prove -> submit.
       */
      balanceTx: async (tx: any, _ttl?: Date) => {
        const recipe = await wallet.balanceTransaction(tx, []);
        console.log(`  balanced; proving recipe: ${recipe.type}`);
        const proven = await wallet.proveTransaction(recipe);
        console.log('  proven');
        return proven;
      },
    },
    midnightProvider: {
      submitTx: async (tx: any) => {
        const id = await wallet.submitTransaction(tx);
        console.log('  submitted; transaction identifier:', id);
        return id;
      },
    },
  } as any;

  // --- Deploy --------------------------------------------------------------
  console.log(`Deploying ShadowVote to ${NETWORK_ID} — proving takes a while …`);
  const deployed = await deployContract(providers, {
    compiledContract,
    privateStateId: 'shadowVotePrivateState',
    initialPrivateState: createPrivateState(adminSk),
    // No `args`: the contract's constructor() takes no parameters.
  });

  const address = deployed.deployTxData.public.contractAddress;
  console.log('\n✅ Deployed. Contract address:', address);
  console.log(`   Explorer: https://explorer.${NETWORK_ID}.midnight.network/contracts/${address}`);
  console.log('\nNext: paste this address into frontend/src/lib/contractService.ts');

  await wallet.close();
}

main().catch((err) => {
  console.error('Deploy failed:', err);
  if (err && typeof err === 'object') {
    console.error('Error details:', JSON.stringify(err, Object.getOwnPropertyNames(err), 2));
  }
  process.exit(1);
});
